// THE `trends` COMMAND — a TRUST TRENDS page: how far SDA is from reality, how much it covers, and whether every
// change is an improvement, at a glance, WITH HISTORY. Unlike `fidelity.ts` (a pure function of the live corpus),
// this reads no corpus at all: the data source is the cheapest honest one available — no new infra, no
// time-series store. Every commit on the CURRENT branch that touched docs/FIDELITY.md already carries a committed
// headline (fitted %, out-of-sample %, scored points, corpus size, capabilities mix), generated by `fidelity.ts`
// at that moment. This script walks that git history, parses each commit's headline DEFENSIVELY (the format has
// already drifted once across history and will again — a commit whose headline doesn't match the expected shape
// is SKIPPED, never mis-parsed, and the skip is counted and printed), and renders a fully self-contained static
// page (inline CSS + inline hand-rolled SVG charts, no JS, no external requests, light theme) to
// app/web/public/trust.html — shipped on the Pages site at /trust.html, alongside the app, as a static asset.
//
// This is a STANDALONE CLI. It is never imported by fidelity.ts and never pulled into fidelity.test.ts or any
// freshness lint: it depends on git history, which a CI checkout (shallow clone, squash-merge) may not carry in
// full, and its output is not a pure function of anything checked in (it is a function of TIME — more commits
// land, the page changes). Regenerate by hand after a docs/FIDELITY.md-changing commit:
//
//   pnpm trends            # (from calibration/) regenerate app/web/public/trust.html and print the parsed history

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fidelityPath, repoRoot } from './fidelity';

const FIDELITY_REL_PATH = 'docs/FIDELITY.md';
const trustPagePath = (): string => join(repoRoot(), 'app', 'web', 'public', 'trust.html');

// ── one history point, parsed defensively from a single commit's committed headline ────────────────────────────
export interface HistoryPoint {
  readonly sha: string;
  readonly shortSha: string;
  readonly date: string; // ISO 8601 commit date (%cI)
  readonly fittedPct: number;
  readonly oosPct: number;
  readonly scoredPoints: number;
  readonly corpusArchitectures: number;
  readonly validated: number;
  readonly verified: number;
  readonly sourced: number;
  readonly noAnchor: number;
  readonly totalCapabilities: number;
}

function git(args: readonly string[]): string {
  return execFileSync('git', args, { cwd: repoRoot(), encoding: 'utf8' });
}

/** Every commit that touched docs/FIDELITY.md on the current branch, OLDEST first (so the charts read left→right
 *  as time moving forward, matching the table below them). */
function fidelityCommits(): { readonly sha: string; readonly shortSha: string; readonly date: string }[] {
  const out = git(['log', '--format=%H%x09%h%x09%cI', '--reverse', '--', FIDELITY_REL_PATH]).trim();
  if (out === '') return [];
  return out.split('\n').map((line) => {
    const parts = line.split('\t');
    if (parts.length !== 3) throw new Error(`trends: unexpected 'git log' line shape (expected 3 tab-separated fields): ${line}`);
    // Non-null: the length check above guarantees all three indices are populated (noUncheckedIndexedAccess).
    return { sha: parts[0]!, shortSha: parts[1]!, date: parts[2]! };
  });
}

/**
 * Parse ONE committed docs/FIDELITY.md headline. Returns null — never throws — if the expected shape isn't found;
 * the caller counts skips rather than crashing the whole walk on one drifted commit. Deliberately permissive on
 * markdown decoration (the `**` bold wrapping has moved across history) but strict on locating the numbers in
 * order, so a genuinely different report shape is skipped rather than silently mis-attributed.
 */
export function parseHeadline(text: string): Omit<HistoryPoint, 'sha' | 'shortSha' | 'date'> | null {
  const fitted = text.match(/Performance fidelity \(fitted\)[:*]*\s*([\d.]+)%\s*over\s*(\d+)\s*scored points[^\d]*([\d.]+)%/);
  const corpus = text.match(/Corpus:[*]*\s*(\d+)\s*architectures/);
  const caps = text.match(
    /Engine capabilities \((\d+)\s*total\)[:*]*\s*(\d+)\s*validated\D*?(\d+)\s*verified\D*?(\d+)\s*sourced\D*?(\d+)\s*with[^\d]*no anchor/,
  );
  if (fitted === null || corpus === null || caps === null) return null;
  return {
    fittedPct: Number(fitted[1]),
    scoredPoints: Number(fitted[2]),
    oosPct: Number(fitted[3]),
    corpusArchitectures: Number(corpus[1]),
    totalCapabilities: Number(caps[1]),
    validated: Number(caps[2]),
    verified: Number(caps[3]),
    sourced: Number(caps[4]),
    noAnchor: Number(caps[5]),
  };
}

/** Walk every commit that touched docs/FIDELITY.md and parse its headline. Returns the parsed points (oldest
 *  first) plus how many commits were skipped (unreadable blob or an unparseable headline shape). */
export function loadHistory(): { readonly points: readonly HistoryPoint[]; readonly skipped: number } {
  const commits = fidelityCommits();
  const points: HistoryPoint[] = [];
  let skipped = 0;
  for (const c of commits) {
    let text: string;
    try {
      text = git(['show', `${c.sha}:${FIDELITY_REL_PATH}`]);
    } catch {
      skipped++;
      continue;
    }
    const parsed = parseHeadline(text);
    if (parsed === null) {
      skipped++;
      continue;
    }
    points.push({ sha: c.sha, shortSha: c.shortSha, date: c.date, ...parsed });
  }
  return { points, skipped };
}

// ── honesty badges — pulled from the CURRENT (working-tree) docs/FIDELITY.md wording, not hardcoded, so the
//    glance can never assert something the live report does not (ui-no-absent-feature-filler / single-truth) ────
function badge(label: string, sourceLine: string, expect: RegExp, reasonIfMatch: string): string {
  if (!/UNVALIDATED/.test(sourceLine)) return `${label}: docs/FIDELITY.md no longer flags this UNVALIDATED — recheck before trusting this badge`;
  return expect.test(sourceLine) ? `UNVALIDATED: ${label} (${reasonIfMatch})` : `UNVALIDATED: ${label} (${sourceLine.trim()})`;
}

function honestyBadges(currentFidelityText: string): readonly string[] {
  const costLine = currentFidelityText.match(/\*\*Cost fidelity:\*\*\s*([^\n]+)/)?.[1] ?? '';
  const availLine = currentFidelityText.match(/\*\*Availability fidelity:\*\*\s*([^\n]+)/)?.[1] ?? '';
  return [
    badge('cost', costLine, /no measured bill/i, 'no measured bill'),
    badge('availability/DR', availLine, /no measured DR/i, 'no measured anchor'),
  ];
}

// ── rendering — a fully self-contained static page, inline CSS + inline SVG, no JS, no external requests ───────
const INK = '#1a1d23';
const INK2 = '#4b5263';
const PAPER = '#fbfaf7';
const CARD = '#fff';
const LINE = '#e5e1d8';
const ACCENT = '#0b6e6e'; // teal — "fitted" / "scored points" / sourced-nature
const ACCENT2 = '#b4530a'; // orange — "out-of-sample" / verified-nature (the less-certain reading)
const GOOD = '#2f7d4f'; // green — validated / improving
const BAD = '#b3261e'; // red — regressing
const GREY = '#6b6456'; // grey — unvalidated / no-anchor
const GREY_LINE = '#8a8577';

const esc = (s: string): string => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const pct1 = (n: number): string => `${n.toFixed(1)}%`;
const shortDate = (iso: string): string => iso.slice(5, 10); // MM-DD — the year never changes across this history yet

// chart geometry shared by the two line charts and the stacked-bar chart, so all three read as ONE visual family
const W = 760;
const ML = 56;
const MR = 20;
const MT = 24;
const PLOT_H = 190;
const H = MT + PLOT_H + 76;

function xPos(i: number, n: number): number {
  if (n <= 1) return ML + (W - ML - MR) / 2;
  return ML + (i * (W - ML - MR)) / (n - 1);
}
function yPos(v: number, max: number): number {
  return MT + PLOT_H - (max === 0 ? 0 : (v / max) * PLOT_H);
}
function niceMax(v: number): number {
  return v <= 0 ? 1 : Math.ceil(v * 1.15 * 10) / 10;
}
function tickLabel(v: number): string {
  return Number.isInteger(v) ? String(v) : v.toFixed(1);
}

function axisAndGrid(yMax: number, unit: string): string {
  const L: string[] = [];
  L.push(`<line class="axis" x1="${ML}" y1="${MT}" x2="${ML}" y2="${MT + PLOT_H}"/>`);
  L.push(`<line class="axis" x1="${ML}" y1="${MT + PLOT_H}" x2="${W - MR}" y2="${MT + PLOT_H}"/>`);
  for (const frac of [0, 0.5, 1]) {
    const v = yMax * frac;
    const y = yPos(v, yMax);
    L.push(`<line class="grid" x1="${ML}" y1="${y.toFixed(1)}" x2="${W - MR}" y2="${y.toFixed(1)}"/>`);
    L.push(`<text class="tick" x="${ML - 8}" y="${(y + 4).toFixed(1)}" text-anchor="end">${tickLabel(v)}${unit}</text>`);
  }
  return L.join('\n');
}

function xLabels(history: readonly HistoryPoint[]): string {
  const n = history.length;
  return history
    .map((h, i) => {
      const x = xPos(i, n).toFixed(1);
      const y = MT + PLOT_H + 14;
      return `<text class="tick" x="${x}" y="${y}" text-anchor="end" transform="rotate(-40 ${x} ${y})">${esc(shortDate(h.date))}</text>`;
    })
    .join('\n');
}

/** Chart 1 — "Distance from reality": fitted % + out-of-sample % over history. Lower is better; y starts at 0. */
function chartDistance(history: readonly HistoryPoint[]): string {
  const n = history.length;
  const yMax = niceMax(Math.max(...history.map((h) => h.fittedPct), ...history.map((h) => h.oosPct)));
  const L: string[] = [];
  L.push(
    `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Fitted error and out-of-sample error across ${n} history points, lower is better">`,
  );
  L.push(axisAndGrid(yMax, '%'));
  const fittedPts = history.map((h, i) => `${xPos(i, n).toFixed(1)},${yPos(h.fittedPct, yMax).toFixed(1)}`).join(' ');
  const oosPts = history.map((h, i) => `${xPos(i, n).toFixed(1)},${yPos(h.oosPct, yMax).toFixed(1)}`).join(' ');
  L.push(`<polyline fill="none" stroke="${ACCENT2}" stroke-width="2.2" points="${oosPts}"/>`);
  L.push(`<polyline fill="none" stroke="${ACCENT}" stroke-width="2.4" points="${fittedPts}"/>`);
  history.forEach((h, i) => {
    const x = xPos(i, n);
    const yF = yPos(h.fittedPct, yMax);
    const yO = yPos(h.oosPct, yMax);
    L.push(`<circle cx="${x.toFixed(1)}" cy="${yO.toFixed(1)}" r="3.4" fill="#fff" stroke="${ACCENT2}" stroke-width="2"/>`);
    L.push(`<circle cx="${x.toFixed(1)}" cy="${yF.toFixed(1)}" r="3.4" fill="#fff" stroke="${ACCENT}" stroke-width="2"/>`);
    L.push(`<text class="pt" x="${x.toFixed(1)}" y="${(yF + 14).toFixed(1)}" text-anchor="middle" fill="${ACCENT}">${pct1(h.fittedPct)}</text>`);
    L.push(`<text class="pt" x="${x.toFixed(1)}" y="${(yO - 7).toFixed(1)}" text-anchor="middle" fill="${ACCENT2}">${pct1(h.oosPct)}</text>`);
  });
  L.push(xLabels(history));
  const ly = MT + PLOT_H + 56;
  L.push(`<line x1="${ML}" y1="${ly}" x2="${ML + 14}" y2="${ly}" stroke="${ACCENT}" stroke-width="2.4"/>`);
  L.push(`<text class="lbl" x="${ML + 20}" y="${ly + 4}">fitted error %</text>`);
  L.push(`<line x1="${ML + 150}" y1="${ly}" x2="${ML + 164}" y2="${ly}" stroke="${ACCENT2}" stroke-width="2.2"/>`);
  L.push(`<text class="lbl" x="${ML + 170}" y="${ly + 4}">out-of-sample %</text>`);
  L.push('</svg>');
  return L.join('\n');
}

/** Chart 2 — "Measured coverage": scored points + corpus architectures over history. Higher is better; y starts
 *  at 0. In the corpus so far every scored ground-truth point comes from a distinct architecture, so the two
 *  series currently coincide exactly — drawn as a thicker backdrop line (corpus) with a thinner foreground line
 *  (scored points) so both remain visible even where they sit on the same pixels, and the caption says so. */
function chartCoverage(history: readonly HistoryPoint[]): string {
  const n = history.length;
  const yMax = niceMax(Math.max(...history.map((h) => h.scoredPoints), ...history.map((h) => h.corpusArchitectures)));
  const L: string[] = [];
  L.push(
    `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Scored points and corpus architectures across ${n} history points, higher is better">`,
  );
  L.push(axisAndGrid(yMax, ''));
  const corpusPts = history.map((h, i) => `${xPos(i, n).toFixed(1)},${yPos(h.corpusArchitectures, yMax).toFixed(1)}`).join(' ');
  const scoredPts = history.map((h, i) => `${xPos(i, n).toFixed(1)},${yPos(h.scoredPoints, yMax).toFixed(1)}`).join(' ');
  L.push(`<polyline fill="none" stroke="${GREY_LINE}" stroke-width="4" stroke-linejoin="round" points="${corpusPts}"/>`);
  L.push(`<polyline fill="none" stroke="${ACCENT}" stroke-width="2" points="${scoredPts}"/>`);
  history.forEach((h, i) => {
    const x = xPos(i, n);
    const yC = yPos(h.corpusArchitectures, yMax);
    const yS = yPos(h.scoredPoints, yMax);
    const s = 3.6;
    L.push(`<rect x="${(x - s).toFixed(1)}" y="${(yC - s).toFixed(1)}" width="${(2 * s).toFixed(1)}" height="${(2 * s).toFixed(1)}" fill="#fff" stroke="${GREY_LINE}" stroke-width="2"/>`);
    L.push(`<circle cx="${x.toFixed(1)}" cy="${yS.toFixed(1)}" r="3.2" fill="#fff" stroke="${ACCENT}" stroke-width="2"/>`);
    L.push(`<text class="pt" x="${x.toFixed(1)}" y="${(yS - 8).toFixed(1)}" text-anchor="middle" fill="${ACCENT}">${h.scoredPoints}</text>`);
  });
  L.push(xLabels(history));
  const ly = MT + PLOT_H + 56;
  L.push(`<circle cx="${ML + 6}" cy="${ly}" r="3.2" fill="#fff" stroke="${ACCENT}" stroke-width="2"/>`);
  L.push(`<text class="lbl" x="${ML + 16}" y="${ly + 4}">scored points</text>`);
  L.push(`<rect x="${ML + 130}" y="${ly - 4}" width="8" height="8" fill="#fff" stroke="${GREY_LINE}" stroke-width="2"/>`);
  L.push(`<text class="lbl" x="${ML + 144}" y="${ly + 4}">corpus architectures</text>`);
  L.push('</svg>');
  return L.join('\n');
}

/** Chart 3 — "Evidence behind the capabilities": stacked bars (validated/verified/sourced/no-anchor out of the
 *  total) per history point. Validated is drawn at the base (0 baseline, easiest segment to compare across bars)
 *  and its count is called out in bold directly above its segment — the emphasized share. */
function chartEvidence(history: readonly HistoryPoint[]): string {
  const n = history.length;
  const yMax = Math.max(...history.map((h) => h.totalCapabilities));
  const barW = Math.min(34, (W - ML - MR) / n - 14);
  const L: string[] = [];
  L.push(`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Capability evidence mix (validated, verified, sourced, no anchor) across ${n} history points">`);
  L.push(axisAndGrid(yMax, ''));
  history.forEach((h, i) => {
    const cx = xPos(i, n);
    const x = cx - barW / 2;
    const segs: readonly { readonly v: number; readonly color: string }[] = [
      { v: h.validated, color: GOOD },
      { v: h.verified, color: ACCENT2 },
      { v: h.sourced, color: ACCENT },
      { v: h.noAnchor, color: GREY },
    ];
    let yCursor = MT + PLOT_H;
    for (const seg of segs) {
      const segH = (seg.v / yMax) * PLOT_H;
      if (segH > 0) L.push(`<rect x="${x.toFixed(1)}" y="${(yCursor - segH).toFixed(1)}" width="${barW.toFixed(1)}" height="${segH.toFixed(1)}" fill="${seg.color}"/>`);
      yCursor -= segH;
    }
    const validatedTopY = MT + PLOT_H - (h.validated / yMax) * PLOT_H;
    L.push(`<text class="ptb" x="${cx.toFixed(1)}" y="${(validatedTopY - 5).toFixed(1)}" text-anchor="middle" fill="${GOOD}">${h.validated}</text>`);
  });
  L.push(xLabels(history));
  const ly = MT + PLOT_H + 56;
  const legend: readonly { readonly label: string; readonly color: string }[] = [
    { label: 'validated', color: GOOD },
    { label: 'verified', color: ACCENT2 },
    { label: 'sourced', color: ACCENT },
    { label: 'no anchor', color: GREY },
  ];
  let lx = ML;
  for (const item of legend) {
    L.push(`<rect x="${lx}" y="${ly - 9}" width="11" height="11" fill="${item.color}"/>`);
    L.push(`<text class="lbl" x="${lx + 16}" y="${ly}">${item.label}</text>`);
    lx += 16 + item.label.length * 6.6 + 20;
  }
  L.push('</svg>');
  return L.join('\n');
}

function bigNumber(label: string, current: number, previous: number | undefined, higherIsBetter: boolean, unit: string): string {
  const value = unit === '%' ? pct1(current) : String(current);
  if (previous === undefined) return `<div class="bn"><div class="bn-label">${esc(label)}</div><div class="bn-value">${value}</div><div class="bn-delta">first recorded point</div></div>`;
  const delta = current - previous;
  const improving = higherIsBetter ? delta > 0 : delta < 0;
  const regressing = higherIsBetter ? delta < 0 : delta > 0;
  const arrow = delta === 0 ? '→' : delta > 0 ? '▲' : '▼';
  const cls = delta === 0 ? 'flat' : improving ? 'good' : regressing ? 'bad' : 'flat';
  const deltaText = unit === '%' ? `${arrow} ${Math.abs(delta).toFixed(1)} pt` : `${arrow} ${Math.abs(delta)}`;
  return `<div class="bn"><div class="bn-label">${esc(label)}</div><div class="bn-value">${value}</div><div class="bn-delta ${cls}">${deltaText} vs previous point</div></div>`;
}

function renderPage(history: readonly HistoryPoint[], skipped: number, badges: readonly string[]): string {
  if (history.length === 0) throw new Error('renderPage: history must be non-empty (the caller checks this before rendering)');
  const last = history[history.length - 1]!; // non-null: guarded by the length check above
  const prev = history.length > 1 ? history[history.length - 2] : undefined;
  const rows = history
    .map(
      (h) =>
        `<tr><td>${esc(h.date)}</td><td class="mono">${esc(h.shortSha)}</td><td>${pct1(h.fittedPct)}</td><td>${pct1(h.oosPct)}</td><td>${h.scoredPoints}</td><td>${h.corpusArchitectures}</td></tr>`,
    )
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SDA — Trust &amp; Fidelity Trends</title>
<style>
  :root{--ink:${INK};--ink2:${INK2};--paper:${PAPER};--card:${CARD};--line:${LINE};--accent:${ACCENT};--accent2:${ACCENT2};--good:${GOOD};--bad:${BAD};--grey:${GREY}}
  *{box-sizing:border-box}
  body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.6 "Segoe UI",Charter,Georgia,serif}
  header{background:linear-gradient(135deg,#0e2f3a,#1c6e7a);color:#fff;padding:40px 24px 32px}
  .w{max-width:960px;margin:0 auto;padding:0 24px}
  h1{font:600 30px/1.2 "Segoe UI",system-ui,sans-serif;margin:0 0 8px}
  .sub{font:15px/1.5 "Segoe UI",sans-serif;opacity:.92;max-width:760px}
  .meta{font:12px/1.4 "Segoe UI",sans-serif;opacity:.72;margin-top:14px;text-transform:uppercase;letter-spacing:.1em}
  h2{font:600 21px/1.3 "Segoe UI",system-ui,sans-serif;margin:40px 0 6px;color:#0e3540}
  .cap{font:13.5px/1.5 "Segoe UI",sans-serif;color:var(--ink2);margin:0 0 14px}
  section{margin-bottom:6px}
  .bignums{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px;margin:24px 0}
  .bn{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px 18px}
  .bn-label{font:12px "Segoe UI",sans-serif;color:var(--ink2);text-transform:uppercase;letter-spacing:.06em}
  .bn-value{font:600 32px "Segoe UI",sans-serif;margin:4px 0 6px;color:var(--ink)}
  .bn-delta{font:12.5px "Segoe UI",sans-serif;color:var(--ink2)}
  .bn-delta.good{color:var(--good);font-weight:600}
  .bn-delta.bad{color:var(--bad);font-weight:600}
  .badges{display:flex;flex-wrap:wrap;gap:10px;margin:10px 0 30px}
  .badge{background:#fdf2e2;color:var(--accent2);font:12.5px/1.4 "Segoe UI",sans-serif;font-weight:600;padding:7px 12px;border-radius:7px;border:1px solid #f0dcb8}
  figure{margin:14px 0 30px;background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px 16px 8px}
  figure svg{display:block;max-width:100%;height:auto}
  figcaption{font:13px/1.5 "Segoe UI",sans-serif;color:var(--ink2);margin-top:8px;padding-bottom:4px}
  .axis{stroke:#c9c4b8;stroke-width:1}
  .grid{stroke:#eceadf;stroke-width:1}
  .tick{font:10.5px "Segoe UI",sans-serif;fill:#8a8577}
  .lbl{font:12px "Segoe UI",sans-serif;fill:var(--ink2)}
  .pt{font:9.5px "Segoe UI",sans-serif}
  .ptb{font:700 12px "Segoe UI",sans-serif}
  table{border-collapse:collapse;width:100%;margin:10px 0 40px;font:14px/1.5 "Segoe UI",sans-serif;background:var(--card)}
  .scroll{overflow-x:auto}
  th{background:#0e3540;color:#fff;text-align:left;padding:8px 12px;font-weight:600}
  td{border-bottom:1px solid var(--line);padding:8px 12px}
  tr:nth-child(even) td{background:#faf8f3}
  .mono{font-family:"Cascadia Code",Consolas,monospace;font-size:12.5px}
  footer{max-width:960px;margin:0 auto;padding:0 24px 40px;font:12.5px "Segoe UI",sans-serif;color:var(--ink2)}
  @media (prefers-color-scheme: dark){
    body{background:#14171c;color:#e7e5df}
    .bn,figure,table{background:#1b1f26;border-color:#2c313a}
    th{background:#0b232a}
    td{border-color:#2c313a}
    tr:nth-child(even) td{background:#20242c}
    .badge{background:#3a2c14;border-color:#5a441e}
    .cap,.bn-delta,.lbl,footer{color:#b7b2a5}
  }
</style>
</head>
<body>
<header>
  <div class="w">
    <h1>SDA — Trust &amp; Fidelity Trends</h1>
    <div class="sub">Three questions, one glance: how far is SDA from measured reality, how much of the engine does that evidence actually cover, and does every change move both numbers the right way? Read straight from the committed history of <code>docs/FIDELITY.md</code> — never estimated, never re-derived.</div>
    <div class="meta">Generated from ${esc(last.shortSha)} · ${esc(last.date.slice(0, 10))}${skipped > 0 ? ` · ${skipped} commit(s) skipped (unparseable headline)` : ''}</div>
  </div>
</header>
<div class="w">

<h2>Now</h2>
<p class="cap">The current headline, each with its delta vs the previous recorded point (not vs the start of history).</p>
<div class="bignums">
  ${bigNumber('Fitted error', last.fittedPct, prev?.fittedPct, false, '%')}
  ${bigNumber('Out-of-sample error', last.oosPct, prev?.oosPct, false, '%')}
  ${bigNumber('Scored points', last.scoredPoints, prev?.scoredPoints, true, '')}
  ${bigNumber('Corpus architectures', last.corpusArchitectures, prev?.corpusArchitectures, true, '')}
</div>

<div class="badges">
  ${badges.map((b) => `<span class="badge">${esc(b)}</span>`).join('\n  ')}
</div>

<h2>Distance from reality</h2>
<p class="cap">Fitted error (against the corpus) and out-of-sample error (leave-one-out) over time. Lower is better; y starts at 0.</p>
<figure>${chartDistance(history)}<figcaption>Fitted error is what the best-fit tunables achieve against the corpus it was fit on; out-of-sample is the honest generalization check (leave-one-out) — it stays higher because most of these ${last.corpusArchitectures} architectures have mostly-disjoint tunables and cannot yet cross-validate each other. READ THIS CHART TOGETHER WITH THE COVERAGE CHART BELOW: the error is measured against a growing corpus, so a rise that coincides with new architectures is the honest cost of harder, more diverse ground truth (0.6% over 3 easy points is a weaker claim than ${pct1(last.fittedPct)} over ${last.scoredPoints}) — the signal to watch is error rising while coverage stands still.</figcaption></figure>

<h2>Measured coverage</h2>
<p class="cap">Scored ground-truth points and corpus architectures over time. Higher is better; y starts at 0.</p>
<figure>${chartCoverage(history)}<figcaption>The two series currently coincide exactly — every corpus architecture so far contributes exactly one scored ground-truth point, so the thin foreground line (scored points) tracks the thick backdrop line (corpus architectures) pixel-for-pixel. That is a property of the corpus today, not a guarantee: a future entry could add multiple scored metrics, or none.</figcaption></figure>

<h2>Evidence behind the capabilities</h2>
<p class="cap">Of the ${last.totalCapabilities} engine capabilities, how many are validated (measured residual), verified (analytic anchor only), sourced (cited quota/price/SLA), or carry no anchor at all — stacked per history point, validated called out in bold.</p>
<figure>${chartEvidence(history)}<figcaption>Validated sits at the 0 baseline in every bar so its height is directly comparable across history. The visible shifts are reclassifications (a family's evidence nature was named more precisely) as much as new evidence — read the per-capability table in <code>docs/FIDELITY.md</code> for which.</figcaption></figure>

<h2>Audit trail</h2>
<p class="cap">The raw parsed history behind the three charts above, oldest → newest (same order as the x-axis). Every row is one commit that changed <code>docs/FIDELITY.md</code>; every number is a straight regex extraction, never recomputed.</p>
<div class="scroll">
<table>
<thead><tr><th>Date</th><th>Commit</th><th>Fitted</th><th>Out-of-sample</th><th>Scored points</th><th>Corpus</th></tr></thead>
<tbody>
${rows}
</tbody>
</table>
</div>

</div>
<footer>Source: <code>git log -- docs/FIDELITY.md</code> on the current branch, parsed by <code>calibration/src/trends.ts</code>. This page is generated, not hand-edited — regenerate with <code>pnpm trends</code> (from <code>calibration/</code>).${skipped > 0 ? ` ${skipped} commit(s) touching the file were skipped because their headline did not match the expected shape.` : ''}</footer>
</body>
</html>
`;
}

// ── CLI entry ────────────────────────────────────────────────────────────────────────────────────────────────
function main(): void {
  const { points, skipped } = loadHistory();
  if (points.length === 0) {
    console.error('trends: no parseable docs/FIDELITY.md history found on this branch — nothing to render.');
    process.exitCode = 1;
    return;
  }
  const currentFidelityText = readFileSync(fidelityPath(), 'utf8');
  const badges = honestyBadges(currentFidelityText);

  writeFileSync(trustPagePath(), renderPage(points, skipped, badges), 'utf8');

  console.log('SDA trust trends — parsed history (oldest → newest)\n');
  console.log('date                      | sha     | fitted | oos    | points | corpus');
  console.log('--------------------------|---------|--------|--------|--------|-------');
  for (const p of points) {
    console.log(
      `${p.date.padEnd(25)} | ${p.shortSha.padEnd(7)} | ${pct1(p.fittedPct).padEnd(6)} | ${pct1(p.oosPct).padEnd(6)} | ${String(p.scoredPoints).padEnd(6)} | ${p.corpusArchitectures}`,
    );
  }
  console.log(`\n${points.length} points parsed, ${skipped} commit(s) skipped.`);
  console.log('\nWrote app/web/public/trust.html');
}

// CLI entry only — import-safe so the fidelity.ts idiom (path helpers importable without side effects) holds here
// too, even though nothing currently imports this module.
if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
