// @algorithm NHPP arrival sampling by inversion (rate profiles)
// @problem Generate arrivals of a non-homogeneous Poisson process whose rate follows a periodic,
//   piecewise-linear load curve, consuming exactly ONE uniform per arrival so a flat profile stays
//   byte-identical to plain exponential sampling and the RNG stream never drifts.
// @approach Time-change/inversion: draw E ~ Exp(1) and advance to the time where the integrated rate
//   grows by E; for a piecewise-linear rate the integral is piecewise-quadratic with a closed-form
//   per-segment inverse, so inversion is exact and rejection-free. Multipliers are normalized at read
//   (divide by the period mean) so a generator's level keeps meaning the period's MEAN rate.
// @complexity O(k) per arrival and per mean/peak read, for k profile vertices (linear segment scan;
//   profiles are a handful of drawn points, never hot).
// @citations Çinlar, "Introduction to Stochastic Processes" (1975) — time-change/inversion; Lewis &
//   Shedler 1979 (thinning — the documented fallback for non-piecewise-linear profiles).
// @invariants Effective multiplier m(t)/mean has mean 1 by construction; exactly one uniform consumed
//   per arrival; a flat profile reduces byte-for-byte to exponential sampling; evaluation wraps
//   periodically for any t >= 0.
// @where-tested engine/sim/src/profile.test.ts

// THE RATE-PROFILE MODULE — the ONE home of load-curve arithmetic. A profile is a
// periodic, piecewise-linear MULTIPLIER over a period, pure timing data in the network's own unit (seconds) —
// no domain vocabulary. Every consumer shares THESE evaluators (the DES's NHPP arrivals below, content's sim
// projection, and any scalar reader of the mean/peak), so interpolation, normalize-at-read and the peak factor
// can never drift between the simulator and the projections.
//
// NORMALIZE-AT-READ (load-curves tension 1): the stored points are exactly what was drawn; readers divide by the
// drawn mean over the period, so the EFFECTIVE multiplier m̂(t) = m(t)/m̄ has mean 1 by construction and a
// generator's level keeps meaning the period's MEAN rate. The peak factor k = max(m)/m̄ is the single derived
// scalar the numeric passes consume.
//
// NHPP SAMPLING BY INVERSION (load-curves §6.2 change 1, tension 4): arrivals of a non-homogeneous Poisson
// process with rate λ(t) = rate · m̂(t) are generated by the time-change/inversion method (Çinlar, "Introduction
// to Stochastic Processes", 1975; Poisson point process simulation): draw E ~ Exp(1) — ONE uniform, exactly
// today's draw — and advance to the t where the integrated rate Λ grows by E. For piecewise-linear λ(t), Λ is
// piecewise-quadratic with a closed-form per-segment inverse, so inversion is EXACT, rejection-free, and keeps
// the RNG stream aligned (one uniform per arrival). The standard alternative — THINNING (P. A. W. Lewis &
// G. S. Shedler, "Simulation of nonhomogeneous Poisson processes by thinning", Naval Research Logistics
// Quarterly 26(3), 1979) — is the documented FALLBACK for any future non-piecewise-linear profile: it would
// consume a variable number of uniforms per arrival (every candidate above the majorizing rate costs a draw),
// which breaks the byte-level "flat profile ≡ today" identity and wastes draws on peaky curves; inversion is
// chosen precisely so a FLAT profile reduces byte-for-byte to today's exponential sampling (see nextArrivalDelay).

/** One vertex of a rate profile: at time `t` (seconds into the period) the drawn multiplier is `m` (≥ 0). */
export interface RateProfilePoint {
  readonly t: number;
  readonly m: number;
}

/**
 * A periodic, piecewise-linear multiplier profile: `points` sorted strictly by `t` ∈ [0, periodS), linear
 * interpolation between vertices, wrapping from the last vertex back to the first at `t = periodS`. Pure shape:
 * it owns no rate — a consumer multiplies its own mean rate by the NORMALIZED value m(t)/m̄. Well-formedness
 * (sortedness, m ≥ 0, some m > 0 so m̄ > 0) is the caller's contract, validated where profiles are authored
 * (engine-core `loadCurveProblem` for the drawn curve; content converts hours → seconds losslessly).
 */
export interface RateProfile {
  readonly periodS: number;
  readonly points: readonly RateProfilePoint[];
}

/** The drawn multiplier m(t) at an absolute time `t` (any t ≥ 0 — reduced into the period), interpolating
 *  linearly between vertices and wrapping periodically. A single point is a flat profile. */
export function profileValue(p: RateProfile, t: number): number {
  const pts = p.points;
  const first = pts[0] as RateProfilePoint;
  if (pts.length === 1) return first.m;
  const x = ((t % p.periodS) + p.periodS) % p.periodS; // reduce into [0, period) (defensive for negative t)
  // Find the segment [pts[i], pts[i+1]) containing x; before the first vertex, the WRAP segment (last → first+period)
  // covers it (shifted back one period). Linear scan — profiles are a handful of drawn vertices, never hot.
  if (x < first.t) {
    const last = pts[pts.length - 1] as RateProfilePoint;
    const span = p.periodS - last.t + first.t;
    return last.m + ((x + p.periodS - last.t) / span) * (first.m - last.m);
  }
  for (let i = 0; i < pts.length - 1; i++) {
    const a = pts[i] as RateProfilePoint;
    const b = pts[i + 1] as RateProfilePoint;
    if (x < b.t) return a.m + ((x - a.t) / (b.t - a.t)) * (b.m - a.m);
  }
  const last = pts[pts.length - 1] as RateProfilePoint;
  const span = p.periodS - last.t + first.t;
  return last.m + ((x - last.t) / span) * (first.m - last.m);
}

/** The DRAWN mean m̄ over one period — the trapezoid integral of the piecewise-linear multiplier (including the
 *  wrap segment) divided by the period. This is the normalize-at-read divisor: effective m̂(t) = m(t)/m̄. */
export function profileMean(p: RateProfile): number {
  const pts = p.points;
  if (pts.length === 1) return (pts[0] as RateProfilePoint).m;
  let area = 0;
  for (let i = 0; i < pts.length - 1; i++) {
    const a = pts[i] as RateProfilePoint;
    const b = pts[i + 1] as RateProfilePoint;
    area += ((a.m + b.m) / 2) * (b.t - a.t);
  }
  const first = pts[0] as RateProfilePoint;
  const last = pts[pts.length - 1] as RateProfilePoint;
  area += ((last.m + first.m) / 2) * (p.periodS - last.t + first.t); // the wrap segment closes the period
  return area / p.periodS;
}

/** The DRAWN peak max(m) — a piecewise-linear maximum is always at a vertex. */
export function profilePeak(p: RateProfile): number {
  let peak = 0;
  for (const pt of p.points) peak = Math.max(peak, pt.m);
  return peak;
}

/** The PEAK FACTOR k = max(m)/m̄ — how many times busier the worst instant is than the period's mean (doc:
 *  load-curves §3, fig. 1). A flat profile has k = 1. The single derived scalar the numeric passes consume. */
export function peakFactorOf(p: RateProfile): number {
  return profilePeak(p) / profileMean(p);
}

/** Is the profile FLAT — every vertex at the same multiplier? A flat profile's effective m̂ is EXACTLY 1
 *  (m/m̄ = m/m), so NHPP sampling reduces to the homogeneous case, byte-for-byte (see nextArrivalDelay). */
export function isFlatProfile(p: RateProfile): boolean {
  const first = (p.points[0] as RateProfilePoint).m;
  return p.points.every((pt) => pt.m === first);
}

/**
 * The next NHPP arrival DELAY from absolute time `now`, by exact inversion (see the module header): find the
 * smallest Δ > 0 with ∫ₙₒwⁿᵒʷ⁺ᐩ rate · m(u)/m̄ du = E, where E is the caller's Exp(1) draw (`−ln(1−u)` — one
 * uniform, drawn by the caller so THIS module stays RNG-free and the DES's stream stays aligned).
 *
 * FLAT ⇒ TODAY, BYTE-FOR-BYTE (load-curves tension 4, the sacred identity): for a flat profile m̂ ≡ 1 exactly,
 * so the delay is `E / rate` — literally the same IEEE expression as today's exponential draw
 * `-Math.log(1 - u) / rate` (the caller passes E = -Math.log(1 - u); dividing that value by `rate` is the
 * identical operation in the identical order). The flat short-circuit below makes the reduction EXACT rather
 * than statistical, which is what turns the compatibility gate into a testable byte-identity.
 *
 * Non-flat: walk the piecewise-linear segments from `now`; on a segment where the effective rate is linear
 * λ(u) = λ̂·(a + b·s) (s the offset into the segment, λ̂ = rate/m̄), the integrated rate over Δs is
 * λ̂·(a·Δs + b·Δs²/2) — piecewise-quadratic with a closed-form positive root, so the inversion is exact and
 * rejection-free. Zero-rate stretches accumulate nothing and are skipped (the arrival lands after them). The
 * loop always terminates: each full period accumulates exactly `rate · periodS` (> 0) of integrated rate.
 */
export function nextArrivalDelay(p: RateProfile, rate: number, now: number, expDraw: number): number {
  if (isFlatProfile(p)) return expDraw / rate; // m̂ ≡ 1 exactly ⇒ the homogeneous draw, byte-for-byte
  const mean = profileMean(p);
  const scaled = rate / mean; // λ̂ — the drawn multiplier's rate scale after normalize-at-read
  let remaining = expDraw; // integrated-rate budget still to accumulate
  let t = now;
  for (;;) {
    // The current segment: [segStart, segEnd) in absolute time, with m linear from m0 to m1 across it.
    const x = ((t % p.periodS) + p.periodS) % p.periodS;
    const seg = segmentAt(p, x);
    const segRemainS = seg.span - seg.offset; // seconds left on this segment from t
    const m0 = seg.m0 + (seg.offset / seg.span) * (seg.m1 - seg.m0); // multiplier at t
    const slope = (seg.m1 - seg.m0) / seg.span; // dm/ds on this segment
    // Integrated rate over the REST of this segment: λ̂·(m0·Δ + slope·Δ²/2) at Δ = segRemainS.
    const segArea = scaled * (m0 * segRemainS + (slope * segRemainS * segRemainS) / 2);
    if (segArea < remaining) {
      remaining -= segArea;
      t += segRemainS;
      continue;
    }
    // The arrival lands inside this segment: solve λ̂·(m0·Δ + slope·Δ²/2) = remaining for the positive root.
    const need = remaining / scaled;
    if (slope === 0) return t + need / m0 - now; // constant stretch (m0 > 0 here, else segArea were 0 < remaining)
    const disc = m0 * m0 + 2 * slope * need;
    const delta = (Math.sqrt(Math.max(disc, 0)) - m0) / slope;
    return t + delta - now;
  }
}

/** The segment of the profile containing period-time `x`: its start multiplier `m0`, end multiplier `m1`, full
 *  `span` (s) and the `offset` of x into it. Handles the wrap segment (last vertex → first vertex + period). */
function segmentAt(p: RateProfile, x: number): { m0: number; m1: number; span: number; offset: number } {
  const pts = p.points;
  const first = pts[0] as RateProfilePoint;
  if (pts.length === 1) return { m0: first.m, m1: first.m, span: p.periodS, offset: x };
  const last = pts[pts.length - 1] as RateProfilePoint;
  const wrapSpan = p.periodS - last.t + first.t;
  if (x < first.t) return { m0: last.m, m1: first.m, span: wrapSpan, offset: x + p.periodS - last.t };
  for (let i = 0; i < pts.length - 1; i++) {
    const a = pts[i] as RateProfilePoint;
    const b = pts[i + 1] as RateProfilePoint;
    if (x < b.t) return { m0: a.m, m1: b.m, span: b.t - a.t, offset: x - a.t };
  }
  return { m0: last.m, m1: first.m, span: wrapSpan, offset: x - last.t };
}
