// The MCP server `instructions` (sent at `initialize`) — the top-level guide an agent reads BEFORE using the
// toolset: what SDA is, which tool to reach for, and the recommended end-to-end FLOWS. Keeping this here (one
// string, shared by the stdio server and relayed through the bridge) is how we describe "which tool for what"
// in MCP itself, so the agent works efficiently instead of rediscovering the toolset call-by-call.
//
// LAYERED (owner directive 2026-07-04, "ai nie wie co robić i jak"): a short MAP first (which tool for what), then
// a complete FLOW CATALOG — EVERY executable job start-to-finish as a concrete call sequence, because flows (not
// tool lists) are what an agent lacks. The catalog is machine-pinned: flows.test.ts parses every `calls:` line and
// proves (a) every one of the 55 tools appears in ≥1 flow, (b) no flow names a tool that does not exist, and (c)
// the error-recovery flows quote the REAL error strings the tools emit. So this guide cannot silently drift from
// the surface. NOTATION for the catalog: one line per job — `calls:` the exact sequence joined by → (each arrow is
// one tool call, with concrete args), then ⇒ the result you get back, then `sees:` what moves on the human's canvas.
export const SDA_INSTRUCTIONS = `SDA — System Design Assistant. You drive a LIVE, COMPUTED architecture canvas. The engine evaluates every design (throughput · latency · availability · durability · cost · overflow) and runs BACKWARDS with EXACT solvers (size, repair, synthesize whole topologies). GOLDEN RULE: let the ENGINE do the thinking — state intent and apply a verified result; do NOT reason component-by-component or place/size things by hand when a coarse tool can. Never compute numbers (concurrency, replicas, cost) yourself — name a goal and let optimize/repair/synthesize fill them. Every result is computed, not guessed — trust the verdicts, and if a call errors, its text names the next action (follow it; never read the repo to learn the toolset).

LEAST EFFORT FIRST — pick the coarsest tool that fits, so you specify (and reason about) as little as possible:
  auto_architect (requirements only)  >  synthesize (you give the shape only)  >  apply_design (you give types + wires)  >  add_component/connect/set_config (one at a time — last resort).

WHAT THE HUMAN SEES: every mutating tool changes the live canvas. Over the FILE transport (VS Code / CLI), the canvas only moves after save_design writes the open file — an unsaved change is invisible to the human, and every mutating result carries a '⚠ unsaved' reminder line until you save (do not finish a job with it still showing). Over the BROWSER transport there is no file; the canvas is the live design and updates as you call tools.

═══ THE TOOL MAP (which tool for what) ═══

DESIGN — prefer these; one call returns a VERIFIED, sized, cost-ranked result:
• auto_architect{throughput, shape?, slos?} — design from REQUIREMENTS ALONE ("design X for N req/s"). shape ∈ {web, cached-read}. Returns ranked whole designs.
• synthesize{fixed, slots, wires, slos} — design a SHAPE you lay out as slots ({id, family}); the engine fills, sizes, ranks each. Use when you know the topology but not the components/sizes.
• apply_design{instances, wires, slos?} — build a design you ALREADY know in ONE call. WIRES: ports are OPTIONAL — write [from,to] and the engine uses each node's only data port; name a port ONLY where a node has several (a service's separate db/cache outputs): [from,port,to]. Atomic: any error applies NOTHING and lists EVERY problem at once — fix them all, retry once. Returns the live verdicts.

VERIFY — read the design's truth:
• evaluate — the everyday verdict on the CURRENT design: {feasible, violations, system, verdicts}. Scalar/forward; a percentile (p99) SLO reads 'unknown' here — it needs simulate. No traffic origin ⇒ it says so and names the fix (never a false green).
• simulate — the TRUE tail (discrete-event sim): end-to-end p50/p95/p99 + per-tier saturation + goodput/errorRate/amplification. Turns a p99 SLO from 'unknown' into a real ok/violation. LOAD STAGES: when a generator declares periodic cycles (set_transform {kind:'generate', level, cycles}), the same read ALSO returns loadStages — the two-tier transient over the auto-derived season (ρ-envelope + worst window + honest mean bill + %-over-capacity from the analytic sweep, plus the survival verdict proven at the worst window by the DES). Absent for a flat design.
• envelope — how far the CURRENT design can be pushed before an SLO breaks, and what breaks first (no demand needed).
• reliability{target?, rpoSeconds?, rtoSeconds?} — AWS Well-Architected availability/DR advice (sourced). NOT a provisioning knob — optimize cannot raise nines; use this.

IMPROVE — change the design to meet/beat its goals:
• optimize{node?, key, direction, scope?} — size the provisioning knobs to min/max a metric under all SLOs. scope:'system' = the WHOLE-DESIGN total of the key (the full bill, off-path branches included; node then optional).
• repair — the MINIMAL knob change to make every SLO hold (needs at least one SLO, else it declines with guidance).
• explain_infeasible — the exact shortfall when no sizing can work (reach for it when repair says infeasible).
• compare_options{node} — swap ONE component: ranked drop-in alternatives (same family, each sized). "Is Fargate cheaper than Lambda here?"
  → optimize/repair PROPOSE and STORE a result; enact it in ONE call with apply_solution (no transcribing set_config).

REQUIREMENTS — declare what "good" means (then evaluate/simulate judge it):
• set_slo{node, key, min/target/max} — a scalar band; or {node, key:'tailLatency', percentiles:{p99:300}} for the tail (verified by simulate); or {key:'cost', max, scope:'system'} for a WHOLE-SYSTEM promise (no node — the quantity is global: the full bill, off-path branches included; judged as a scope:'system' verdict and enforced by repair/optimize — cost is the ONLY system-scoped key). An END-TO-END availability promise is just an availability band on the flow's TERMINAL node — {node:'db', key:'availability', min:0.999} — judged against that node's CUMULATIVE availability (every dependency on the path multiplied down to it), so a band on the terminal IS the end-to-end path promise (repair/optimize verify it CHECK-ONLY, since availability rides the discrete deploymentMode/replicas redundancy, not a sized knob). A cost band ON a node bounds that node's BRANCH cost only. scope is {node, system} — there is no flow scope.
• set_guarantee_slo{source, terminal, dimension, atLeast} — consistency/ordering/delivery on a FLOW; evaluate verdicts it with the root-cause hop + a computed same-family swap fix.
• set_lag_slo{source, terminal, maxMs} — a CDC/replication propagation deadline (async waits INCLUDED); resolved by simulate.
  → each has a clear_* twin (clear_guarantee_slo / clear_lag_slo / clear_range). A scalar set_slo is removed by overwriting it (no clear twin).

DELIVER:
• generate_doc{format?:'markdown'|'html'} — the architect's DELIVERABLE from the verified model (requirements/SLOs, capacity table, C4 view, cost table, reliability tiers, bottleneck analysis). 'markdown' (default, diffable RFC) or 'html' (self-contained review-board report). Generate AFTER the design verifies.

EDIT PRIMITIVES (incremental, when a coarse tool won't do): add_component · remove_node · connect · set_config · set_type · set_label · set_description · add_group · group_node · rename_node · undo · redo.

═══ FLOW CATALOG — every job, start to finish (read once, then act) ═══
Each line: calls: the sequence (→ = one call, concrete args) ⇒ what comes back · sees: what moves on the canvas. Find your job's group; run the sequence.

── BUILD (make a design) ──
▸ From requirements alone — calls: auto_architect{throughput:5000, shape:'web', slos:[{key:'latency',cmp:'<=',value:300}]} → apply_design → evaluate ⇒ ranked verified designs, then the winner built with {feasible,violations,system,verdicts} · sees: the canvas fills with the sized design
▸ A design you already know — calls: apply_design{instances:[{id:'client',type:'client.web',config:{throughput:5000}},{id:'app',type:'compute.service'},{id:'db',type:'db.postgres'}], wires:[['client','app'],['app','db','db','in']], slos:[{node:'db',key:'latency',cmp:'<=',value:300}]} → evaluate ⇒ the whole verified picture in one call · sees: the built, evaluated canvas
▸ A topology you shaped — calls: synthesize{fixed:[{id:'client',type:'client.web',config:{throughput:5000}}], slots:[{id:'svc',family:'compute'},{id:'db',family:'db'}], wires:[['client','out','svc','in'],['svc','db','db','in']], slos:[{node:'db',key:'latency',cmp:'<=',value:300}]} → apply_design → evaluate ⇒ ranked filled+sized designs, then the winner built · sees: the canvas fills with the chosen topology
▸ Brick by brick (last resort) — calls: add_component{id:'client',type:'client.web'} → connect{fromNode:'client',fromPort:'out',toNode:'db',toPort:'in'} → set_config{node:'client',key:'throughput',value:5000} → evaluate ⇒ verdicts on the hand-built graph · sees: each node/edge appears as you go
▸ Discover before you build — calls: list_components → describe_component{type:'db.postgres'} → list_protocols → apply_design ⇒ the full type/port/protocol vocabulary, then a correct one-shot build · sees: nothing until apply_design, then the design
▸ A custom block the catalog lacks — calls: define_component{json:'{"type":"custom.oracle","ports":[{"name":"db","dir":"in","accepts":["oracle-tns"]}]}'} → add_component{id:'ora',type:'custom.oracle'} → connect{fromNode:'app',fromPort:'db',toNode:'ora',toPort:'db'} → evaluate ⇒ the custom type placed and wired · sees: the new node on the canvas
▸ A design that arrived as JSON text — calls: import_project{json:'{"schema":3,...}'} → evaluate ⇒ the loaded design + its verdicts · sees: the canvas replaced with the pasted design
▸ Read the whole design out — calls: get_project ⇒ the canonical .sda.json text (nodes/wires/config/SLOs/classes/worlds/ranges) · sees: no change (a read)

── EDIT (change an existing design) ──
▸ Rename a node — calls: rename_node{id:'db1', to:'orders_db'} → evaluate ⇒ every wire/SLO reference rewritten, re-verified · sees: the node id changes on the canvas
▸ Remove a node (and its wires) — calls: remove_node{id:'cache'} → evaluate ⇒ the node and edges gone, re-verified · sees: the node + its wires disappear
▸ Label / describe a node — calls: set_label{id:'db1', label:'Orders DB'} → set_description{id:'db1', description:'system of record for orders'} → generate_doc ⇒ the friendly name + purpose, carried into the C4 doc · sees: the node shows its label + description
▸ Swap a component type — calls: compare_options{node:'svc'} → set_type{id:'svc', type:'compute.fargate'} → repair → apply_solution → evaluate ⇒ ranked alternatives, the swap applied and re-sized · sees: the node changes type, then its sizing
▸ Amplify/reduce flow on a port — calls: set_transform{node:'logger', port:'out', fn:'ratio', value:100} → evaluate ⇒ downstream sees the true (100×) load · sees: the port shows its transform, loads update
▸ Generate traffic AT a port (a cron / emitter / migration source) — calls: set_transform{node:'cron', port:'out', fn:'generate', value:200} → evaluate ⇒ the port originates 200 req/s of its own (it consumes the node's capacity, then flows downstream); add a periodic shape with cycles:[{periodS:86400, stages:[{durationS:28800,multiplier:0.5},{durationS:28800,multiplier:1.8}]}] — or in one call name a preset:'diurnal' (flat·spike·ramp-up·diurnal·on-off-burst·quarterly-report) — and simulate plays it (the level is the BASELINE ×1) · sees: the origin's load appears downstream
▸ Split a routing fan-out per wire — calls: set_wire_transform{fromNode:'gw', fromPort:'out', toNode:'checkout', toPort:'in', fn:'prob', value:0.3} → evaluate ⇒ each edge carries its real share (no false overload) · sees: the edge shows 30%, loads rebalance
▸ Frame a tier / VPC / zone — calls: add_group{id:'vpc', label:'Production VPC'} → group_node{node:'orders_db', group:'vpc'} → generate_doc ⇒ a boundary that also becomes a C4 boundary · sees: a labelled box frames the member nodes
▸ Step back / forward — calls: undo → redo ⇒ the last change reverted, then re-applied · sees: the canvas steps back, then forward

── REQUIREMENTS (declare what "good" means) ──
▸ A scalar SLO — calls: set_slo{node:'db', key:'latency', max:300} → evaluate ⇒ the band judged ok/violation against the computed value · sees: the node shows its requirement + verdict
▸ A tail (p99) SLO — calls: set_slo{node:'gw', key:'tailLatency', percentiles:{p99:300}} → simulate ⇒ 'unknown' on the scalar pass becomes a real ok/violation from the DES tail · sees: the p99 verdict on the terminal
▸ A whole-SYSTEM cost promise (global — no node) — calls: set_slo{key:'cost', max:30000, scope:'system'} → evaluate → repair → apply_solution ⇒ a scope:'system' verdict against the WHOLE bill (every component summed, off-path branches included — the same total optimize scope:'system' minimizes), and the backward search now holds the ceiling (a binding budget escalates to the exact reference MIP, labeled) · sees: the System panel shows the whole-system promise + verdict
▸ An end-to-end availability promise — calls: set_slo{node:'db', key:'availability', min:0.999} on the flow's TERMINAL node → evaluate ⇒ a node verdict against that node's CUMULATIVE availability (every dependency on the path multiplied down to it — the number the doc's reliability section prints, so a band on the terminal IS the end-to-end path promise) · sees: the terminal's Promises row shows the promise + verdict
▸ A flow guarantee (consistency/ordering/delivery) — calls: set_guarantee_slo{source:'client', terminal:'worker', dimension:'ordering', atLeast:'per-key'} → evaluate → clear_guarantee_slo{source:'client', terminal:'worker', dimension:'ordering'} ⇒ the promise judged with its root-cause hop + a same-family swap fix, then cleared · sees: the flow shows its guarantee verdict
▸ A replication/CDC lag deadline — calls: set_lag_slo{source:'srcdb', terminal:'aurora', maxMs:2000} → simulate → clear_lag_slo{source:'srcdb', terminal:'aurora'} ⇒ the async-inclusive mean lag measured (a real ok/violation), then cleared · sees: the flow shows its lag verdict

── IMPROVE (make it meet its goals) ──
▸ Fix every SLO with the minimal change — calls: repair → apply_solution → evaluate ⇒ the smallest knob changes that go green, applied in one call · sees: the sized knobs update, verdicts turn green
▸ Optimize a metric under the SLOs — calls: optimize{node:'db', key:'cost', direction:'min'} → apply_solution → evaluate ⇒ the cheapest config that still holds every SLO, applied · sees: the knobs settle at their optimum
▸ Size the fleet for the peak — calls: set_transform{node:'gw', port:'out', fn:'generate', value:2000, preset:'diurnal'} → set_slo{node:'db', key:'latency', max:300} → repair → apply_solution → evaluate ⇒ the peak is a FIXED native input (the declared load is never a tunable — the solver cannot throttle traffic to fake a cheaper design), so repair/optimize size the provisioning knobs to survive the WORST window, applied · sees: the knobs settle to carry the peak
▸ Understand why it can't be met — calls: repair → explain_infeasible ⇒ the exact per-SLO shortfall no sizing can close · sees: no change (a diagnosis)
▸ Availability / disaster-recovery advice — calls: reliability{target:0.9999} → reliability{rpoSeconds:60, rtoSeconds:300} ⇒ the nines tier each flow meets + the sourced remedy, then the recommended DR tier · sees: no change (sourced advice, not a knob)

── CHECK (analyses on the current design) ──
▸ Everyday verdict — calls: evaluate ⇒ {feasible, violations, system, verdicts} · sees: the live numbers the human already sees
▸ The true tail — calls: simulate ⇒ p50/p95/p99 + per-tier saturation + goodput/errorRate/amplification · sees: no change (a read)
▸ Model a daily peak & check survival ("does my design survive the daily peak?") — calls: set_transform{node:'gw', port:'out', fn:'generate', value:2000, preset:'diurnal'} (a LEVEL baseline ×1 + a CYCLE shape — name a preset [flat·spike·ramp-up·diurnal·on-off-burst·quarterly-report] or give explicit cycles:[{periodS, stages:[{durationS, multiplier}]}]; several cycles multiply, separate generators sum) → simulate ⇒ the loadStages two-tier transient over the auto-derived season: rhoEnvelope over time + worstWindow{atS, rho, node} (which node saturates at the peak and WHEN) + costMeanUsdMonth (the honest mean bill) + pctWindowsViolating (the %-of-span over capacity) (Tier-1 analytic), plus transient.verdict {survives, recoversInS, peakBacklog{node,value,atS}, p99During/AfterMs, lostRequests} PROVEN at the worst window by the DES (Tier-2 measured). Read survives + peakBacklog to answer "does it hold at the peak?" · sees: no change (a read)
▸ Which node breaks at the peak — calls: set_transform{node:'gw', port:'out', fn:'generate', value:2000, preset:'diurnal'} → evaluate ⇒ each node judged against its WORST window (peak-aware): a node calm at the mean but saturated at its declared peak reads a REAL saturation violation and feasible turns false; the offending node is named in the verdict (same worst-window ρ the loadStages worstWindow and the design doc report) · sees: the canvas flags the node that saturates at the peak
▸ How far it can be pushed — calls: envelope ⇒ the max sustained load per origin, what breaks first, the queueing knee · sees: no change (a read)
▸ Model a store/proxy's queueing tail under load ("why is my p99 bad?") — calls: describe_component{type:'proxy.rds'} → set_config{node:'proxy', key:'connectionPool', value:50} → set_config{node:'proxy', key:'connectionHeldMs', value:40} → set_slo{node:'proxy', key:'tailLatency', percentiles:{p99:300}} → simulate ⇒ the proxy's p99 climbs as offered×held nears the pool (an M/M/pool station of capacity pool/held; past it the borrow queue reneges → per-tier drops + errorRate); a concurrency-bound store queues the SAME way via its concurrency knob, so tune that instead on a db/service · sees: the p99 + tier saturation update
▸ Model a CPU-bound front-end (a framework/proxy that saturates on CPU before its DB) — calls: describe_component{type:'proxy.nginx'} → set_config{node:'front', key:'cpuCores', value:4} → set_config{node:'front', key:'cpuTimePerRequestMs', value:2} → evaluate → simulate ⇒ the front-end forms an M/M/cores CPU station (capacity = cores ÷ (cpuTime ÷ 1000)); its ceiling is whichever resource binds first, so it shows as the LOW-load bottleneck in ρ/overflow and its p99 climbs with load · sees: the front-end's utilisation + tail update

── REQUEST CLASSES (a cyclic each-to-each mesh) ──
▸ Carve the mesh into named flows — calls: declare_class{id:'orders', origins:[{node:'A',rps:800}], wires:[['A','B']]} → set_class_membership{class:'orders', wire:['B','A'], member:true} → set_class_origin{class:'orders', node:'A', rps:900} → list_classes → evaluate ⇒ per-class acyclic flows judged per class (the mesh now computes) · sees: the design evaluates per class instead of refusing
▸ Drop the classes — calls: remove_class{id:'orders'} → evaluate ⇒ back to the single implicit river · sees: the class overlay is gone

── WHAT-IF WORLDS + UNCERTAINTY (the assumption model) ──
▸ Author + compare the pessimistic/real/optimistic trio — calls: envelope → derive_scenarios → evaluate_scenarios ⇒ the trio filled from THIS design's capacity, then the metrics×worlds matrix side by side · sees: the System panel shows the worlds
▸ Declare a world, freeze a value, then unfreeze — calls: declare_scenario{id:'peak', name:'Black Friday', overrides:[{node:'client',key:'throughput',value:12000}]} → set_scenario_value{scenario:'peak', node:'client', key:'throughput', value:15000} → evaluate_scenarios → clear_scenario_value{scenario:'peak', node:'client', key:'throughput'} ⇒ a named world, its value frozen at 15000, compared, then returned to derived tracking · sees: the world appears + updates in the panel
▸ List then remove a world — calls: list_scenarios → remove_scenario{id:'peak'} ⇒ the declared worlds, then one removed · sees: the world disappears from the panel
▸ Reset a world to a clean slate — calls: derive_scenarios → set_scenario_value{scenario:'real', node:'client', key:'throughput', value:9999} → reset_scenario{id:'real'} ⇒ the trio, one value frozen by editing, then that world WIPED back to its freshly-derived values (the frozen edit dropped; a custom world would clear to base instead) · sees: the world's numbers snap back to derived in the panel
▸ A fix robust across ALL worlds — calls: derive_scenarios → repair{worlds:'all'} → apply_solution → evaluate_scenarios ⇒ the smallest change that holds every SLO in every world, applied · sees: the knobs update; every world goes green
▸ The cheapest design across ALL worlds — calls: optimize{node:'db', key:'cost', direction:'min', worlds:'all'} → apply_solution ⇒ the cost-optimal config that survives every world, applied · sees: the knobs settle robustly
▸ Turn conclusions into distributions (Monte Carlo) — calls: set_range{node:'client', key:'throughput', lo:1500, hi:3000} → uncertainty{n:1000, seed:7} → clear_range{node:'client', key:'throughput'} ⇒ per-metric median+p5/p95, per-SLO confidence, a tornado of what drives the spread, then the range cleared · sees: the System panel's Uncertainty · Monte Carlo block (after save on the file transport)
▸ Blur a range around a named world — calls: declare_scenario{id:'peak', overrides:[{node:'client',key:'throughput',value:12000}]} → set_range{node:'client', key:'throughput', lo:1500, hi:3000} → uncertainty{scenario:'peak'} ⇒ the cloud centred on that world's point · sees: the panel resamples around the world

── FILES (the "AI moves my canvas" loop) ──
▸ Edit the human's open file live — calls: import_design{path:'my-design.sda.json'} → set_range{node:'client', key:'throughput', lo:1500, hi:3000} → uncertainty → save_design ⇒ the open file loaded, edited, written back · sees: the canvas LIVE-RELOADS to your change on save
▸ save_design is unavailable/disabled in your client — calls: get_project ⇒ the canonical .sda.json text; write it VERBATIM to the SAME path with your own file tool (byte-for-byte — never reformat, reindent, reorder or hand-edit it) · sees: the canvas live-reloads when the open file changes on disk, exactly as if save_design wrote it

── DELIVER (the artifact) ──
▸ Ship the design doc — calls: generate_doc{format:'html'} ⇒ the self-contained review-board report (or 'markdown' for a diffable RFC) from the verified model · sees: no canvas change (it returns the document text)

── ERROR RECOVERY (after a guided error, the exact next calls; the quoted text is what you'll see) ──
▸ "no traffic origin" (evaluate found nothing driving the design) — calls: set_transform{node:'svc', port:'out', fn:'generate', value:5000} → evaluate ⇒ throughput/latency/cost stop being vacuous (the generator is the taught origination path; set_config{node, key:'assumedRps', value} is the legacy equivalent, and a client.* node is a preset) · sees: the numbers populate
▸ "did you mean" (add_component/apply_design got an unknown type) — calls: list_components → add_component{id:'db', type:'db.postgres'} ⇒ the real type placed · sees: the node appears with the correct type
▸ "applied NOTHING" (apply_design is atomic — it listed every problem) — calls: apply_design{instances:[{id:'client',type:'client.web'},{id:'svc',type:'compute.service'},{id:'db',type:'db.postgres'}], wires:[['client','svc'],['svc','db','db','in']]} ⇒ fix EVERY listed problem and retry in ONE call · sees: the whole design lands at once
▸ "has no port" / "ambiguous" (connect/apply_design port) — calls: describe_component{type:'compute.service'} → connect{fromNode:'svc', fromPort:'db', toNode:'orders_db', toPort:'in'} ⇒ the real port named, wire drawn · sees: the edge appears
▸ "no config knob" (set_config typo) — calls: describe_component{type:'db.postgres'} → set_config{node:'db', key:'concurrency', value:200} ⇒ the real knob set · sees: the value updates
▸ "is not an SLO-able metric" (set_slo typo) — calls: set_slo{node:'db', key:'latency', max:300} ⇒ the requirement stored on a real computed metric · sees: the SLO + verdict appear
▸ "is not a system-scoped quantity" (set_slo scope:'system' with a per-node key) — calls: set_slo{node:'db', key:'latency', max:300} → set_slo{key:'cost', max:30000, scope:'system'} ⇒ the node quantity lands on its node; only the global quantities (cost) carry the system scope · sees: both promises appear with their scopes
▸ "no SLOs declared" (repair had nothing to make hold) — calls: set_slo{node:'db', key:'latency', max:300} → repair ⇒ a requirement, then the minimal fix · sees: the knobs size to meet it
▸ "proven infeasible" (no sizing can satisfy the SLOs) — calls: explain_infeasible → set_slo{node:'db', key:'latency', max:500} ⇒ the exact shortfall, then a loosened SLO (or raise a ceiling) · sees: the relaxed requirement, now reachable
▸ "no backward-search proposal" (apply_solution before a search) — calls: repair → apply_solution ⇒ a proposal to enact, then applied · sees: the sized knobs update
▸ "not yet available" (a search/sim declined under request classes) — calls: remove_class{id:'orders'} → repair ⇒ the single-river design searchable again (or evaluate per class) · sees: the class overlay clears
▸ "unknown protocol" (define_component used an invented id) — calls: list_protocols → define_component{json:'{"type":"custom.oracle","ports":[{"name":"db","dir":"in","accepts":["oracle-tns"]}]}'} ⇒ a real protocol id, component defined · sees: the custom type becomes placeable
▸ "no uncertainty ranges declared" (uncertainty before any range) — calls: set_range{node:'client', key:'throughput', lo:1500, hi:3000} → uncertainty ⇒ a soft input to sample, then the distributions · sees: the Monte-Carlo block lights up
▸ "no wire" (set_wire_transform/set_class_membership named an undrawn edge) — calls: connect{fromNode:'gw', fromPort:'out', toNode:'checkout', toPort:'in'} → set_wire_transform{fromNode:'gw', fromPort:'out', toNode:'checkout', toPort:'in', fn:'prob', value:0.3} ⇒ the edge drawn first, then shaped · sees: the wire appears, then its split
▸ save the first time with no import — calls: save_design{path:'my-design.sda.json'} ⇒ a path is required until something is imported to default to · sees: the file is written (and the canvas reloads if it is the open one)

═══ CONCEPTS ═══
TRAFFIC ORIGINS — not every design has a client. ANY node can originate load, at a PORT: set_transform{node, port, fn:'generate', value} (a DB→DB migration, a cron worker; a node may relay on some ports and generate on others). Generated traffic consumes the node's own capacity, then exits the port. Optional periodic cycles on the generator shape it over time (each cycle = {periodS, stages:[{durationS, multiplier}]}; the level is the BASELINE ×1; simulate plays the shape). set_config{node, key:'assumedRps', value} is legacy sugar for the same thing; clients (client.*) are just a preset. Worlds/Monte-Carlo still override the level via assumedRps. With NO origin anywhere there is nothing to compute — evaluate says so and names the fix.
FLOW TRANSFORMS — a node relays 1:1 by default; real ones amplify/reduce (1 req → 100 log lines). set_transform{node, port, fn, value} per port (closed set: ratio·batch·cap·window·prob·generate; omit fn to clear). One out port feeding SEVERAL wires broadcasts the full rate to each (right for pub/sub, wrong for routing) — use set_wire_transform per edge for a split (70/30 ⇒ prob 0.7 / prob 0.3); generate is port-only (a wire cannot originate).
PEAKS (load over time) — a generator is a LEVEL (baseline ×1) + an optional CYCLE shape: name a preset:'diurnal' (flat·spike·ramp-up·diurnal·on-off-burst·quarterly-report) OR give explicit cycles:[{periodS, stages:[{durationS, multiplier}]}] (stages ramp linearly to their multiplier; Σ durationS ≤ periodS). Several cycles on one port MULTIPLY (superposition); separate generators SUM. The peak is just traffic in a given season — a FIXED input, never a solver tunable. Both reads are peak-aware: evaluate judges each node against its WORST window (a node green at the mean but broken at its peak reads a real violation, feasible turns false); simulate adds the loadStages two-tier transient (Tier-1 ρ-envelope over the auto-derived season + worst window + honest mean bill + %-over-capacity, Tier-2 the survival verdict PROVEN at the worst window by the DES). Silent for a flat design (no cycles ⇒ no loadStages — the no-filler rule). repair/optimize size the knobs to survive the peak (they cannot lower the declared load).
REQUEST CLASSES — an each-to-each mesh (A↔B) is cyclic as one river; declare_class carves it into named acyclic flows that share the nodes (declare_class / set_class_membership / set_class_origin / remove_class / list_classes). evaluate then judges per class; backward search + simulate decline honestly under classes (not yet certified).
NAMED WORLDS — declare_scenario / set_scenario_value / clear_scenario_value / remove_scenario / reset_scenario / list_scenarios / evaluate_scenarios / derive_scenarios: fact-assumption overrides (a pessimistic/real/optimistic trio) evaluated side by side. set_scenario_value FREEZES a value you edit; clear_scenario_value UNFREEZES it back to derived tracking; reset_scenario WIPES a world (a trio world back to freshly-derived, a custom world to base) — the non-preserving twin of derive_scenarios.

═══ CAPABILITIES YOU CAN MODEL (config knobs → effect) ═══
describe_component LISTS a node's knobs; this says what each DOES to the result. Set them with set_config (or apply_design per-node config). These are live modeling levers that materially move the verdicts and are easy to miss — reach for them before concluding a design is fine.
QUEUEING TAIL — a tier's p99 comes from its M/M/c queueing station, never a fixed number. A concurrency-bound store/service queues via \`concurrency\` (servers = concurrency × replicas/maxUnits): its tail rises with load, and raising concurrency lowers it. A POOLING PROXY has NO concurrency knob — its tail is driven by its CONNECTION POOL: give it \`connectionPool\` (backend-connection budget) + \`connectionHeldMs\` (how long one request holds a connection ≈ the backend's per-query time) + \`maxQueueWaitMs\` (borrow timeout), and simulate runs it as an M/M/pool station of capacity pool/held — its p99 climbs as offered×held approaches the pool, and past the pool requests WAIT then RENEGE past the borrow timeout (per-tier drops + errorRate). evaluate flags the same pressure scalar-side as \`poolOverflow\`. proxy.rds ships this (pool 100, held 30 ms, 120 s borrow). This is why a design green on the MEAN can still miss its p99 under load — always simulate a store/proxy near capacity.
REDUNDANCY (availability) — \`deploymentMode\` (0 single-AZ · 1 Multi-AZ · 2 multi-Region) selects the PUBLISHED SLA: it steps availability UP (RDS 99.5% → 99.95%) and cost UP (Multi-AZ bills the standby ≈ 2×). This is THE availability lever — optimize/repair size CAPACITY and cannot raise nines; set deploymentMode, then read \`reliability\` for the tier each flow meets. db.postgres / db.mysql / db.aurora / compute.asg carry it.
ACT AS A QUEUE — ANY component can BUFFER work, not only a queue block: \`queueMode:1\` + \`drainRate\` (consumer pull, msg/s) + \`retention\` (how long an unconsumed message survives, s) + \`maxBacklog\` (depth before it drops). evaluate then computes \`backlog\` (net accumulation; >0 ⇒ growing without bound ⇒ a violation) and simulate drops past maxBacklog. retention / durability / drain are exactly what separate SQS vs Redis vs Postgres as a queue — a store can be turned into one. queue.* / stream.kafka ship it on.
DOCUMENTED CEILINGS (outage caps) — real account/service limits, sourced as DATA, that fire as a violation the moment load/size crosses them: a serverless fleet's \`accountConcurrency\` (Lambda default 1,000 per region — offered load implies Little's-law concurrency, throttled past the quota as 429s = \`concurrencyOverflow\`); an API gateway's \`throughput\` IS the documented account throttle (10,000 rps → 429); a payload ceiling \`maxItemBytes\` (DynamoDB 400 KB item, SQS 256 KB message) rejects an over-size \`payloadBytes\` as \`payloadOverflow\`. The design's real breaking point, not a guess.
RETRY STORMS — a caller's retry policy on the ORIGINATING node: \`timeoutMs\` (per-attempt deadline; 0 = off) + \`retryCount\` (extra attempts after the first) + \`retryBackoffMs\`. simulate then reports \`amplification\` (attempts ÷ arrivals), \`goodputRps\` (successful work) and \`errorRate\` — and PAST saturation retries LOWER goodput (congestion collapse), never raise it. DES-only (a retry loop is a question about time; evaluate reads these \`unknown\`).
REALISTIC COST — cost is a visible \`unitCost\` base × the driver that GROWS capacity (provisioned \`throughput\`, M/M/c \`concurrency\`, a \`replicas\`/\`requiredUnits\` count, or pay-per-use inflow), so sizing a ceiling to meet an SLO ALWAYS costs money (optimize/repair trade against it — capacity is never free). Add the most-missed bill line, data egress, with \`payloadBytes\` (response size per request) + \`egressUsdPerGb\` on the INTERNET-facing tier → a separate \`egressCost\`. Judge the whole bill with a cost SLO scope:'system'.
LATENCY COMPOSITION — how a node combines its SYNCHRONOUS downstream response times: \`latencyComposition\` 0 = sequential (sum — the default), 1 = parallel/scatter-gather (max, the critical path), 2 = fastest/hedged (min). Set it on a node that fans out to several backends so its response latency reflects the real call pattern instead of assuming everything is serial.
CPU-BOUND TIER — a node's real ceiling can be its CPU, not its concurrency / connection pool / declared throughput: \`cpuCores\` (parallel-execution width — hardware threads or vCPUs it burns at once) + \`cpuTimePerRequestMs\` (CPU time one request costs) make it an M/M/cores station of capacity cores ÷ (cpuTime ÷ 1000). Its ceiling is whichever resource BINDS FIRST — CPU vs concurrency vs pool vs throughput (the lowest) — so a CPU-bound front-end (a web framework, an nginx/Thrift proxy) shows as the bottleneck at LOW load, before any database, and its p99 climbs with load like any M/M/c. evaluate reads the CPU ceiling in ρ/overflow; simulate runs the CPU station's tail. Set both (cores alone or time alone do nothing — a node with neither is byte-identical to before). Two in-series resources are modelled as the binding MIN, not a tandem network (the deep allocator/GC/lock-contention economics stays out of scope).

═══ DISCOVERY (self-sufficient — never read source) ═══
• list_components — every placeable type WITH ports+protocols. • describe_component{type} — one type in full (ports, every set_config knob + default/unit, bands). • list_protocols — the official protocol vocabulary (the ONLY valid port ids). • get_project — the whole current design as canonical .sda.json text.

═══ FILES vs TEXT (two save/load transports) ═══
FILE (VS Code / CLI): import_design{path} loads a workspace .sda.json AND tracks it; save_design{} writes it back → the open canvas LIVE-RELOADS (save_design{path} saves elsewhere). This is the "AI moves my canvas" loop; NEVER hand-assemble the JSON.
FALLBACK — save_design is unavailable/disabled in your client: get_project returns the SAME canonical .sda.json text save_design would write — write it VERBATIM to the same path yourself with your own file tool. Byte-for-byte: never reformat, reindent, reorder keys or hand-edit the text (a "tidied" file breaks the diff and risks corrupting the design); the open canvas live-reloads on the file change just the same.
TEXT (no file access): get_project returns the design as canonical .sda.json text; import_project{json} loads it back. Use these when the design arrives/leaves as inline text.

COMMON TYPES (list_components for the full set): client.web · apigw.rest / gateway.api · compute.service / compute.faas / compute.fargate / compute.cloudrun · db.postgres / db.mysql / db.aurora / db.dynamodb · cache.redis · search.elasticsearch · queue.sqs / queue.rabbitmq / queue.nats · topic.sns · stream.kafka · storage.object · lb.alb · cdn.cloudfront.

NAMING (so you can predict a tool): list_X reads a set · set_X / clear_X write & remove one property · declare_X upserts a named overlay (class/world) · remove_X deletes one (remove_node/remove_class/remove_scenario) · add_X places a canvas entity · a bare verb (evaluate/simulate/repair/optimize/envelope/reliability/uncertainty) runs an analysis. Structured reads/analyses return pretty JSON; discovery tools return compact text.`;
